### ISSUE TITLE
Exit value printed continuously with print_exit_value option enabled

### ISSUE THREAD

**Issue by noctuid** [zdharma/zplugin#193] opened 2019-10-25 23:21 UTC
**Describe the bug**
If I enable `print_exit_value` and run something that has a non-zero exit value, the exit value is printed over and over.

**To Reproduce**
Source zplugin, `setopt print_exit_value`, then run something that has a non-zero exit value (e.g. `[[ -f non-existent-file ]]`).

**Expected behavior**
Exit value is printed once only.

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): `Linux bahamut 5.2.17-1-ck #1 SMP PREEMPT Sat Sep 21 09:34:02 EDT 2019 x86_64 GNU/Linux`

**Additional context**
If I enable xtrace, I get something like this over and over:
```
...
2754010 -zplg-scheduler:73> local __task __idx=0 __count=0 __idx2
2754010 -zplg-scheduler:85> __idx2=1
2754010 -zplg-scheduler:85> __idx2 <= __idx
2754010 -zplg-scheduler:88> ZPLG_RUN[1-correct,__idx-correct]=( )
2754010 -zplg-scheduler:90> return 130
```

**Comment by NICHOLAS85** [comment] 2019-10-25 23:28
I believe this was fixed in https://github.com/zdharma/zplugin/commit/7a2338ab8abf790ba9b1bb00b6c8d86709406c23 for https://github.com/zdharma/zplugin/issues/172 and then reverted in https://github.com/zdharma/zplugin/commit/e3bae96ebcf5ebf9d893eb70a23de399165cfe0a due to https://github.com/zdharma/zplugin/pull/185. Looks like a solution hasn't been created yet.

**Comment by psprint** [comment] 2019-10-25 23:32
I have a solution though through, I'll commit it tomorrow

sob., 26 paź 2019, 01:28 użytkownik NICHOLAS85 <notifications@github.com>
napisał:

**Comment by psprint** [comment] 2019-10-30 18:47
Sorry for the delay. The issue is resolved.

**Comment by noctuid** [comment] 2019-10-30 18:56
Now the exit code is not displayed at all?

**Closed** 2019-10-30 19:03 UTC
