### ISSUE TITLE
zplugin self-update hangs

### ISSUE THREAD

**Issue by jubishop** [zdharma/zplugin#219] opened 2019-11-27 00:26 UTC
**Describe the bug**
When I run `zplugin self-update`, it pulls updates all the way till 2019-11-21 but then just hangs indefinitely. It never finishes.

**To Reproduce**
run `zplugin self-update`

**Expected behavior**
It would eventually finish and return me to the command line.

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Happens on my Linux and Mac machine.

**Comment by psprint** [comment] 2019-11-27 00:31
I cannot reproduce. Do you mean that the zplugin version from 11/21/2019 works but the later ones do not?

**Comment by psprint** [comment] 2019-11-27 00:32
From which Zplugin version do you update?

**Comment by agkozak** [comment] 2019-11-27 00:35
@jubishop Is the last line printed a colon? In my experience, when I run `zplugin self-update` after a long time, there are a lot of `git log` entries, and they're run through `less`. Try pressing `q` -- the update should continue.

**Comment by psprint** [comment] 2019-11-27 00:38
Ah yes, it's possible, given the number of commits that I'm doing recently ;) I didn't add a code that limits the time the `less` is allowed to run to `20` seconds as I did for the regular `update`, maybe I should.

**Comment by psprint** [comment] 2019-12-04 22:56
Closing as an apparent false alarm.

**Closed by psprint** 2019-12-04 22:56 UTC
