### ISSUE TITLE
Allow easily adding local plugins, or plugins managed independently

### ISSUE THREAD

**Issue by intelfx** [zdharma/zplugin#4] opened 2016-04-07 23:03 UTC
Let's suppose I have a plugin that does not come from github (or that I want to manage plugin git trees myself, e. g. as submodules). `zplugin` does not provide any facility to load already existing plugin directories.

~~What I want is a (configurable) path for zplugin to look there for already existing subdirectories and just use those as plugins. E. g. by symlinking into its own `~/.zplugin/_local---$name`.~~

Edit: More precisely (as zplugin does not do any kind of auto-loading previously loaded plugins), I want `zplugin load` to be able to work with local pathes. This is going to be a pretty invasive change as the code does not quite expect slashes in plugin name.

**Comment by akatrevorjay** [comment] 2016-04-10 09:54
@intelfx I've been working on autoloading of previously loaded plugins over here -- https://github.com/psprint/zplugin/pull/5

**Comment by psprint** [comment] 2016-04-14 09:28
Hello
Thank you for the contribution. I will be away from computer for week from now on, will look at the changes after that

**Comment by akatrevorjay** [comment] 2016-04-14 09:56
No worries. Have a good vaca!

**Comment by psprint** [comment] 2016-04-16 08:27
Thinking about this in a little spare time – it is possible to load non-github plugins. Their user name is to be "_local". So one has to enter ~/.zplugin/plugins and create directory "_local---pluginname". This seems like non-convenient, however, zplugin has the "cd" command. It is then sufficient to enter "zplg cd pluginname" to enter ~/.zplugin/plugins/_local---pluginname. There is already one such "local" plugin – "zplugin" – this is how zplugin's completion is provided:

https://asciinema.org/a/emjpcaheolrk2pbe0elsv0l58

Also, the "create" command allows to create "_local" plugins:

https://asciinema.org/a/5ari0i5eks655hzhf5gktwmfb

@akatrevorjay: I'm not sure if your changes utilize what already exists?

**Comment by akatrevorjay** [comment] 2016-05-03 04:24
@psprint What do you mean by utilize what already exists?

**Comment by psprint** [comment] 2016-09-15 11:33
I'm returning to Zplugin within months and much will be added, e.g. 100% robust unload. Working on new plugin currently, already finished a previous one, maybe you would want to have a look:

https://github.com/psprint/zconvey

**Comment by alanpearce** [comment] 2017-05-18 09:10
I can see that local plugins functionality has been implemented, but I think either it, or I am missing something.

If I install something that comes with some `zsh` files (e.g. [motemen/ghq](https://github.com/motemen/ghq) has a completion file at `zsh/_ghq`), `zplugin` still doesn't seem to have a way to "install" these files. I don't want to clone the source, because it's quite possible that the source at `master` doesn't match that of the installed command.

Previously, I was also using `zplug` before, which made this very simple:
```
zplug "${GOPATH:=$HOME/go}/src/github.com/motemen/ghq/zsh/", from:local, if:"[[ -n $commands[ghq] ]]"
```

Whereas, with zplugin's local plugins feature, it seems to me that I would have to create a skeleton plugin with `zplg create` on every device, then symlink the code there myself, for every such plugin? I think it would be really awesome if zplugin were as easy to use as zplug in this regard, or maybe there already is a way, but I just don't see it.

**Comment by psprint** [comment] 2017-05-23 04:48
Ok, I've added "if" ice modifier (https://github.com/zdharma/zplugin#news), having the feature of adding local path to `$fpath` (but in case of Zplugin, it can be managed-completions directory) in back of my head, not sure when this gets clarified, for architecture that bases on `user/plugin` identifiers, but still a nice solution can  be found

**Comment by alanpearce** [comment] 2017-06-09 12:15
Thanks for adding `if`, it will definitely be useful, I'm not sure how it relates to local plugin loading. I was describing how zplug, another manager, allows loading local plugins and asking if zplugin would support something similar, without having to create 'skeleton' plugins.

**Comment by psprint** [comment] 2017-06-09 14:57
I will definitely code this, just now working on adding redis database support to upstream, should end in 5 days.

**Comment by psprint** [comment] 2017-06-13 07:54
Thanks for coming up with this, I have now coded this feature:

```zsh
% zplg load %HOME/github/{directory}
% zplg load /Users/sgniazdowski/github/{directory}
% zplg load %/Users/sgniazdowski/github/{directory}
% zplg creinstall %HOME/github/{directory}
...
```

**Comment by alanpearce** [comment] 2017-06-13 08:16
Works perfectly, thanks!

**Comment by moonrumble** [comment] 2017-12-06 18:18
How does it work if local plugin is not a git repo?

**Comment by psprint** [comment] 2017-12-06 18:22
It doesn't clone directory, but reuses it, so no requirement for repository

**Comment by moonrumble** [comment] 2017-12-06 18:30
I have ~/.zsh directory under which I have 3 files aliash.sh, grml.sh and setupLocal.sh

>  
% zpl load ~/.zsh
> 

Above doesn't work. Shouldn't it load all 3 files. 

Appreciate the quick response.

**Comment by moonrumble** [comment] 2017-12-07 01:08
@psprint Sorry, I looked at the code and file name should be *.plugin.zsh. After I adjusted the plugin name. it is loading correctly.

zpl report still says "No such plugin %/HOME/.zsh".

**Comment by psprint** [comment] 2017-12-07 06:04
> I created 3 plugins alias.plugin.zsh, completion.plugin.zsh and functions.plugin.zh. It only picks up alias.plugin.zsh. Is it by design that it only loads one plugin from the local repo?

Yes this is by design. Plugin has a main file to source. Other user also expected loading multiple files. I might use `src` ice-mod for this, will see.

It should pick up also `*.sh` files. I created 3 such files under `~/.zsh` – `alias.sh`, `grml.sh`, `setupLocal.sh`, then issued `zplg load ~/.zsh`, got message:

```
alias.sh loaded
```

(added print to each file). So `1` file sourced. Then I used `zplg report <TAB>` and chosen `%HOME/.zsh`, report was:

```
Plugin report for %//Users/sgniazdowski/.zsh
--------------------------------------------
Source alias.sh
```

So it looks fine. A trick other user came up with is to do `atinit'local i; for i in grml.sh setupLocal.sh; do source $i; done'`. This might help survive till it will be decided how to extend zplugin so that it does what users expect.

**Comment by moonrumble** [comment] 2017-12-07 06:22
I have just moved everything from zgen to zplugin. Start time with turbo mode is very fast. Thank You!

For now. I have created local.plugin.zsh and source all the zsh files from it. 

Plugin details show up when I use `zpl report <TAB>` and select the local plugin. If I ran `zpl report` it says `No such plugin %/HOME/.zsh`

**Comment by moonrumble** [comment] 2017-12-21 16:27
Hi, 

I am playing a little bit more with the local plugin. Not all the ice mode works on the local plugin. It is looking for the corresponding directory under the plugin directory.

>  zpl ice atload"echo abc"; zpl light ~/.local
> zpl ice atinit'local i; for i in grml.sh setupLocal.sh; do source $i; done'; zpl light ~/.local

Thanks

**Comment by psprint** [comment] 2017-12-22 05:48
@moonrumble It should be fixed now, thanks for reporting

**Comment by moonrumble** [comment] 2017-12-22 17:31
Thank You. This is now working as I expected

> zpl ice atinit'local i; for i in *.zsh; do source $i; done'; zpl light ~/.local

**Closed** 2018-01-09 15:22 UTC
Labels: enhancement, in-progress
