### ISSUE TITLE
The first prompt is missing right prompt

### ISSUE THREAD

**Issue by romkatv** [zdharma/zplugin#167] opened 2019-09-19 09:20 UTC
To reproduce:

```zsh
docker run -e LANG=C.UTF-8 -e TERM -it --rm ubuntu bash -uexc '
  apt update && apt install -y curl git zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
  echo "zplugin ice wait\"!\" atload\"RPROMPT=x\" lucid nocd" >>~/.zshrc
  echo "zplugin snippet /dev/null"                            >>~/.zshrc
  exec zsh'
```

Actual: The first prompt doesn't have right prompt. Prompts after the first do have right prompt, as expected.

![actual](https://user-images.githubusercontent.com/1282067/65231052-43144c80-dacf-11e9-96ad-7c06965eaa26.png)

Expected: All prompts, including the first, have right prompt.

![expected](https://user-images.githubusercontent.com/1282067/65231073-4c9db480-dacf-11e9-920d-c730ef2dd359.png)

**Comment by robobenklein** [comment] 2019-09-19 15:25
![image](https://user-images.githubusercontent.com/5423266/65257855-e8c7bb80-dacf-11e9-977a-18d826b8aa85.png)

```
docker run -e LANG=C.UTF-8 -e TERM -it --rm ubuntu bash -uexc '
  apt update && apt install -y curl git zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
  echo "zplugin ice wait\"!0\" atload\"RPROMPT=x\" silent nocd" >>~/.zshrc
  echo "zplugin snippet /dev/null"                            >>~/.zshrc
  exec zsh'

```

If I add `wait'!0'` and silent, I still get an install message, which seems like even different behaviour, but would explain why the RPROMPT is missing in that case.

**Comment by romkatv** [comment] 2019-09-19 15:47
I should mention that this issue doesn't bother me. I opened it just in case you find the report useful. If you don't consider it worthy of fixing or even looking at, it won't upset me in the slightest if you close the issue or do nothing at all.

**Comment by dylanjm** [comment] 2019-09-19 16:00
I am experiencing this issue. I have tried using `wait'!'` in my `ice` command. I have also tried forcing it by using `reset-prompt`. It's still not reloading my prompt. I have an screen asciinema capture of what I'm talking about. Apologies if it goes slow, it was my first recording. 

[![asciicast](https://asciinema.org/a/vzd94UJ3EUiBasFjySYgM0YDm.svg)](https://asciinema.org/a/vzd94UJ3EUiBasFjySYgM0YDm)

**Comment by romkatv** [comment] 2019-09-19 16:10
@dylanjm This is a different problem. The issue I opened concerns specifically right prompt. If you take my original docker command and replace `RPROMPT` with `PROMPT`, it'll work. If you move `RPROMPT` definition outside of `ice`, it'll also work.

The solution for your problem is simple.

```zsh
source ~/.p10k.zsh
zplugin light romkatv/powerlevel10k
```

If you like your drinks with ice, this should also work:

```zsh
zplugin ice atload'source ~/.p10k.zsh' lucid nocd
zplugin light romkatv/powerlevel10k
```

**Comment by dylanjm** [comment] 2019-09-19 16:12
ahh I see. Apologies, I mistook "right prompt" as "_correct_ prompt".

**Comment by romkatv** [comment] 2019-09-19 16:13
> ahh I see. Apologies, I mistook "right prompt" as "_correct_ prompt".

Bad choice of words on my part. The screenshots should clarify what I meant.

**Comment by psprint** [comment] 2019-09-20 00:17
Thanks for such a well isolated report. The first thought is however that this has something to do with upstream Zsh and that zplugin has no part in it. But I'll still take a closer look.

**Comment by psprint** [comment] 2019-11-10 19:31
Closing as the issue seems to be caused by an upstream bug.

**Closed by psprint** 2019-11-10 19:31 UTC

**Comment by romkatv** [comment] 2019-11-10 19:33
> Closing as the issue seems to be caused by an upstream bug.

In which upstream project is the bug? Could you post a link to the bug report?

**Comment by psprint** [comment] 2019-11-10 23:43
In Zsh. There's no bug report done.
