### ISSUE TITLE
Unable to load plugin from Gitlab

### ISSUE THREAD

**Issue by TeChn4K** [zdharma/zplugin#115] opened 2019-03-18 16:21 UTC
I want to load a plugin from Gitlab with the _from_ ice modifier, but zplugin constantly try to fetch it from Github

```
zplugin ice from"gitlab"
zplugin light foo/bar
```

gives me

```
Downloading foo/bar...
Username for 'https://github.com': 
```

ZSH_VERSION: 5.4.2
Xubuntu 18.04
Zplugin installed today with install.sh script

**Comment by psprint** [comment] 2019-03-19 00:02
I cannot reproduce. Could you try with `from'gl'`?

**Comment by psprint** [comment] 2019-03-19 01:32
I've found the reason, it's fixed now

**Comment by TeChn4K** [comment] 2019-03-19 05:52
It was quick! It's working great now, thank you!

**Closed** 2019-03-19 05:53 UTC
