### ISSUE TITLE
Command of sourced plugin not in hash table

### ISSUE THREAD

**Issue by Gerrit-K** [zdharma/zplugin#157] opened 2019-07-31 10:22 UTC
**Describe the bug**
The plugins `diff-so-fancy` and `forgit` don't seem to work together when loaded in turbo mode. The problem is that `git dsf` uses `diff-so-fancy` while `forgit` doesn't. 

I already started a little bit of debugging myself and observed that `diff-so-fancy` is not in the zsh `hash` table during [forgit's check](https://github.com/wfxr/forgit/blob/master/forgit.plugin.zsh#L8), although it is listed in `$PATH` and `which diff-so-fancy` also returns the correct executable. This is why I believe it's more of a `zplugin` issue than a specific issue with one of the plugins themselves. ***Or*** I'm just doing it [wrong](https://i.kym-cdn.com/photos/images/newsfeed/000/000/122/bush_doing_it_wrong_1.jpg).

**To Reproduce**
See this Dockerfile:
```Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
      git make zsh curl tree vim \
 && chsh -s /usr/bin/zsh \
 && sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"

RUN echo "\n\
zpl ice from'gh-r' as'program'; zpl load 'junegunn/fzf-bin' \n\
zpl ice wait'0a' lucid as'program' pick'bin/git-dsf'; zpl load 'zdharma/zsh-diff-so-fancy' \n\
zpl ice wait'0b' lucid; zpl load 'wfxr/forgit' \n"\
>> /root/.zshrc

WORKDIR /root
CMD zsh
```

Instructions to reproduce:
* wait for all plugins to install
* `cd .zplugin/plugins/wfxr---forgit` (as an example git repository)
* execute for example `git dsf @~~ @` to verify that `diff-so-fancy` is working
* execute for example `glo` to verify that `forgit` doesn't know about `diff-so-fancy`
* in the Dockerfile, replace the line 
  ```zpl ice wait'0a' lucid as'program' pick'bin/git-dsf'; zpl load 'zdharma/zsh-diff-so-fancy' \n\``` 
  with
  ```zpl ice wait'0a' lucid as'program' pick'bin/git-dsf' atload'hash diff-so-fancy=$(which diff-so-fancy)'; zpl load 'zdharma/zsh-diff-so-fancy' \n\```
  to activate the `atload` workaround for `diff-so-fancy` and rebuild the image
* repeat the previous steps -> now `forgit` also works with `diff-so-fancy`

**Versions:**
Should be printed on screen during docker build. At the time of writing:
* zsh: `5.4.2-3ubuntu3.1`
* OS: `Linux be0d4fc76b86 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
I started from the configuration from [NICHOLAS85 from the samples](https://github.com/zdharma/zplugin-configs/blob/master/NICHOLAS85/.zshrc) and adjusted it to my needs.

**Comment by psprint** [comment] 2019-07-31 10:37
An introductory quick check and answer: for me it is working. I get dsf in the glo's preview on the right. I'll investigate more later. Maybe the OS matters (OS X). I'll try with a docker image. But nevertheless if it will reproduce then it will mean a bug in upstream zsh itself, not in zplugin.

**Comment by Gerrit-K** [comment] 2019-07-31 19:29
Alright, thanks for the quick reply! So the bug would be that zsh fails to put dsf into the hash table early enough to let forgit pick it up?

**Comment by psprint** [comment] 2019-07-31 20:16
Yes, I think that's most probable scenario

**Comment by psprint** [comment] 2019-10-16 22:03
Closing as it doesn't reproduce for me and that it looks like an upstream bug.

**Closed by psprint** 2019-10-16 22:03 UTC
Labels: problem, upstream

**Comment by psprint** [comment] 2020-06-13 00:37
I've got back to this issue and discovered, that there's no `diff-so-fancy` in the `forgit.plugin.zsh` file. Why do you expect forgit to use `diff-so-fancy`?
