### ISSUE TITLE
Failed to load zplugin zmod after successful compilation

### ISSUE THREAD

**Issue by ideologysec** [zdharma/zplugin#131] opened 2019-05-20 23:25 UTC
**Describe the bug**
macOS fails to load the compiled zmodule.
```
/Users/user/.zshrc:105: failed to load module `zdharma/zplugin': dlopen(/Users/user/.zplugin/bin/zmodules/Src/zdharma/zplugin.bundle, 9): image not found
```

**To Reproduce**
- install zplugin via shell command
- `zplugin compile-module`
- wait a while (<3 minutes on my 2016 15" MBP laptop)
- add two lines to zshrc:
```
+module_path+=("$HOME/.zplugin/bin/zmodules/Src")
+zmodload zdharma/zplugin

source "$HOME/.zplugin/bin/zplugin.zsh"
zplugin snippet OMZ::plugins/osx/osx.plugin.zsh
```
etc
(I added the pluses to indicate my additions; they are not in the actual zshrc).

**Expected behavior**
The module should be loaded.

**Versions:**
 - $ZSH_VERSION == zsh 5.7.1 (x86_64-apple-darwin18.2.0) [installed via homebrew]
 - uname -a: Darwin localhost 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
 - macOS Mojave 10.14.5

**Additional Information:**
My zshrc is a symlink to a folder elsewhere in my HOME directory, but I don't think or see how, that would make a difference.

**Comment by psprint** [comment] 2019-06-02 16:05
Does the issue persist? If so, then could you paste the output of the compilation?

**Comment by ideologysec** [comment] 2019-06-03 03:18
Yes, it persists. Here's what I hope is the relevant bits (tail end of the log from `zplugin module build`
```
Updated `zsh.mdh'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makemod prefix='/usr/local' exec_prefix='/usr/local' bindir='/usr/local/bin' libdir='/usr/local/lib' MODDIR='/usr/local/lib/zsh/5.3.1-dev-0' infodir='/usr/local/share/info' mandir='/usr/local/share/man' datadir='/usr/local/share' fndir='/usr/local/share/zsh/5.3.1-dev-0/functions' htmldir='/usr/local/share/zsh/htmldoc' runhelpdir='/usr/local/share/zsh/5.3.1-dev-0/help' CC='gcc' CPPFLAGS='-I/usr/local/include' DEFS='-DHAVE_CONFIG_H' CFLAGS='-g -Wall -O3' LDFLAGS='-L/usr/local/lib' EXTRA_LDFLAGS='-rdynamic' DLCFLAGS='-fno-common' DLLDFLAGS='-bundle -flat_namespace -undefined suppress' LIBLDFLAGS='' EXELDFLAGS='' LIBS='-liconv -ldl -ltermcap -lm  -lc' DL_EXT='so' DLLD='gcc' AWK='gawk' ANSI2KNR=': ansi2knr' YODL=': yodl ' YODL2TXT=': yodl2txt' YODL2HTML=': yodl2html' FUNCTIONS_INSTALL='' tzsh='zsh' prep
creating Src/zdharma/Makefile.in
config.status: creating Src/zdharma/Makefile
echo 'timestamp for *.mdd files' > ../Src/modules.stamp
Updated `zplugin.mdh'.
echo 'timestamp for zplugin.mdh against zplugin.mdd' > zplugin.mdhs
gawk -f ../../Src/makepro.awk zplugin.c Src/zdharma > zplugin.syms
gawk: ../../Src/makepro.awk:124: warning: regexp escape sequence `\=' is not a known regexp operator
(echo '/* Generated automatically */'; sed -n '/^E/{s/^E//;p;}' < zplugin.syms) \
             > zplugin.epro
(echo '/* Generated automatically */'; sed -n '/^L/{s/^L//;p;}' < zplugin.syms) \
             > `echo zplugin.epro | sed 's/\.epro$/.pro/'`
Updated `zplugin.mdh'.
gcc -c -I. -I../../Src -I../../Src -I../../Src/Zle -I. -I/usr/local/include -DHAVE_CONFIG_H -DMODULE -g -Wall -O3 -fno-common -o zplugin..o zplugin.c
zplugin.c:1213:49: warning: unused variable 'oarr' [-Wunused-variable]
    char *callback = NULL, *oarr_name = NULL, **oarr = NULL;
                                                ^
zplugin.c:1538:1: warning: unused function 'zp_createhashparam' [-Wunused-function]
zp_createhashparam( char *name, int flags )
^
2 warnings generated.
rm -f zplugin.so
gcc -L/usr/local/lib  -bundle -flat_namespace -undefined suppress -o zplugin.so   zplugin..o    -liconv -ldl -ltermcap -lm  -lc
Module has been built correctly.
To load the module, add following 2 lines to .zshrc, at top:
    module_path+=( "/Users/user/.zplugin/bin/zmodules/Src" )
    zmodload zdharma/zplugin

After loading, use command `zpmod' to communicate with the module.
See `zpmod -h' for more information.
~ 57s ❯
```

**Comment by psprint** [comment] 2019-06-04 13:05
Could you issue following commands:

```zsh
echo "ZPLG_BIN: $ZPLGM[ZPLG_BIN]"
find "$ZPLGM[ZPLG_BIN]" -iname 'zplugin.so'
```

?

**Comment by ideologysec** [comment] 2019-06-05 18:22
> `echo "ZPLG_BIN: $ZPLGM[ZPLG_BIN]"`
`ZPLG_BIN:` (empty)
> `find "$ZPLGM[ZPLG_BIN]" -iname 'zplugin.so'`
`find: : No such file or directory`

**Comment by psprint** [comment] 2019-06-05 20:36
Sorry, the commands should be:

```zsh
echo "ZPLG_BIN: $ZPLGM[BIN_DIR]"
find "$ZPLGM[BIN_DIR]" -iname 'zplugin.so'
```

Nevertheless, if `zplugin.so` exists under the rather expected path, then something else is going on.

**Comment by ideologysec** [comment] 2019-06-07 00:51
```
$ echo "ZPLG_BIN: $ZPLGM[BIN_DIR]"`
ZPLG_BIN: /Users/user/.zplugin/bin
$ find "$ZPLGM[BIN_DIR]" -iname 'zplugin.so'
/Users/user/.zplugin/bin/zmodules/Src/zdharma/zplugin.so
$ otool -L /Users/user/.zplugin/bin/zmodules/Src/zdharma/zplugin.so
/Users/user/.zplugin/bin/zmodules/Src/zdharma/zplugin.so:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
```

[is this relevant at all? ](https://stackoverflow.com/questions/4677044/how-to-use-dylib-in-mac-os-x-c)the error message in terminal seems to indicate not that the binary can't be found,  but that the dyld loader can't find the symbols it's looking for in the zplugin.so file.

`failed to load module `zdharma/zplugin': dlopen(/Users/user/.zplugin/bin/zmodules/Src/zdharma/zplugin.bundle, 9): image not found`

**Comment by Seirdy** [comment] 2019-06-12 16:17
Can confirm; I also have this issue.

[This](https://gitlab.com/Seirdy/dotfiles/blob/master/.zshrc) is my zshrc.

Adding `zmodload zdharma/zplugin` (line 9) to my zshrc on macOS causes a message to appear:

```
/Users/me/.zshrc:9: failed to load module `zdharma/zplugin': dlopen(~/.zplugin/bin/zmodules/Src/zdharma/zplugin.bundle, 9): image not found
```

**Comment by psprint** [comment] 2019-06-12 17:54
@Seirdy: Which Zsh version?

**Comment by RobertAudi** [comment] 2019-06-18 11:44
@psprint Same problem here. Zsh version: `zsh 5.6.2 (x86_64-apple-darwin18.2.0)`

**Comment by codahale** [comment] 2019-06-19 19:11
If you rename `~/.zplugin/bin/zmodules/Src/zdharma/zplugin.so` to `~/.zplugin/bin/zmodules/Src/zdharma/zplugin.bundle`, it appears to work.

**Comment by RobertAudi** [comment] 2019-06-20 06:12
@codahale I can confirm that! I don't know if that's a workaround or a solution but it does get rid of the error.

**Comment by psprint** [comment] 2019-06-20 07:04
@RobertAudi, @Seirdy, @codahale which OS X version do you use?

**Comment by RobertAudi** [comment] 2019-06-20 07:08
@psprint macOS Mojave 10.14.5

As a side note, I added this snippet of code in my `.zshrc`, but I'm not sure it's the best way to do it (ie: I'm not sure I like the way I did it):

```shell
  if [[ ! -a "$ZPLG_HOME/bin/zmodules/Src/zdharma/zplugin.bundle" ]] && [[ -a "$ZPLG_HOME/bin/zmodules/Src/zdharma/zplugin.so" ]]; then
    mv "$ZPLG_HOME/bin/zmodules/Src/zdharma/zplugin.so" "$ZPLG_HOME/bin/zmodules/Src/zdharma/zplugin.bundle"
  fi

  if [[ ! -a "$ZPLG_HOME/bin/zmodules/Src/zdharma/zplugin.bundle" ]]; then
    module_path+=("$HOME/.zplugin/bin/zmodules/Src")

    zmodload zdharma/zplugin
  fi
```

**Comment by psprint** [comment] 2019-07-15 00:24
Could you try with a **single entry** in the `module_path` array? Zsh should then report the proper, related error message. I.e.:

```
module_path=("$HOME/.zplugin/bin/zmodules/Src")
zmodload zdharma/zplugin
```
?

**Comment by RobertAudi** [comment] 2019-07-20 11:33
@psprint Sorry for the late reply.

I just tried adding the zplugin module as the only entry in `module_path`, but I got a similar result:

1. I got the same error reported in this issue
2. I got all sort of failures because other zsh modules could not be loaded

Here is a sample of the output:

```
/Users/rob/.zsh/.zshrc:2: failed to load module `zdharma/zplugin': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zdharma/zplugin.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:66: failed to load module `zsh/termcap': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/termcap.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:66: failed to load module `zsh/terminfo': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/terminfo.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:67: failed to load module `zsh/termcap': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/termcap.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:67: failed to load module `zsh/terminfo': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/terminfo.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:68: failed to load module `zsh/termcap': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/termcap.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:68: failed to load module `zsh/terminfo': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/terminfo.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:69: failed to load module `zsh/termcap': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/termcap.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:69: failed to load module `zsh/terminfo': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/terminfo.bundle, 9): image not found
/Users/rob/.zplugin/bin/zplugin.zsh:143: failed to load module `zsh/zle': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/zle.bundle, 9): image not found
/Users/rob/.zsh/.zshrc:12: failed to load module `zsh/rlimits': dlopen(/Users/rob/.zplugin/bin/zmodules/Src/zsh/rlimits.bundle, 9): image not found
/Users/rob/.zsh/plugins/zplugin.zsh:2: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:6: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:7: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:11: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:12: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:16: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:20: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:24: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:28: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:32: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:33: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:37: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:38: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:41: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:42: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:43: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:45: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.zsh:46: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/fzf.zplugin.zsh:2: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:3: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:4: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:8: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:9: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:13: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:14: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:19: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:20: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:24: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:25: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:28: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/git.zplugin.zsh:29: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/grc.zplugin.zsh:2: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/grc.zplugin.zsh:3: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/macos.zplugin.zsh:3: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/macos.zplugin.zsh:7: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/macos.zplugin.zsh:10: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/ruby.zplugin.zsh:2: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/tmux.zplugin.zsh:3: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/tmux.zplugin.zsh:4: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/tmux.zplugin.zsh:7: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/vim.zplugin.zsh:3: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/vim.zplugin.zsh:4: command not found: zplugin
/Users/rob/.zsh/plugins/zplugin.d/vim.zplugin.zsh:7: command not found: zplugin
```

**Comment by psprint** [comment] 2019-07-20 13:43
Ok, thanks, I now see from where does this come – the DL_EXT configure test returns different values for the provided Zshell and for the module's `configure` script. I've solved this by doing an automatic copy of the `zplugin.so` to the `zplugin.bundle` file, so it should now be fixed.

**Comment by RobertAudi** [comment] 2019-07-20 15:14
@psprint I just check, it works now!

**Comment by psprint** [comment] 2019-07-20 23:04
Great so I'm closing the issue. Thanks for the report!

**Closed by psprint** 2019-07-20 23:04 UTC
Labels: in-progress, known-or-hard, problem
